name: CI
on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - run: cargo test --all-features
      - run: cargo fmt
      - run: cargo clippy --all-targets --all-features
